=== smals-jy/KMEHR-tests/src/transactionFHIRDosage.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/MedicationEntry",
  "definitions": {
    "MedicationEntry": {
      "type": "object",
      "properties": {
        "drugType": {
          "type": "string",
          "enum": [
            "medicinalproduct",
            "substanceproduct",
            "compoundprescription"
          ],
          "description": "Type of drug.\n- \"compoundprescription\" : a free text drug\n- \"medicinalproduct\" : common drug (like Dafalgan)\n- \"substanceproduct\" : substance (like Paracetamol)",
          "examples": ["medicinalproduct"]
        },
        "identifierType": {
          "type": "string",
          "enum": ["CD-VMPGROUP", "CD-INNCLUSTER", "CD-DRUG-CNK", "CD-EAN"],
          "description": "Identifier type of the drug",
          "examples": ["CD-DRUG-CNK"]
        },
        "identifierIntendedType": {
          "type": "string",
          "enum": ["CD-INNCLUSTER", "CD-VMPGROUP"],
          "description": "Identifier type of the intended drug. By default, it is equal to \"identifierType\""
        },
        "identifierDeliveredType": {
          "type": "string",
          "const": "CD-DRUG-CNK",
          "description": "Identifier type of the intended drug. By default, it is equal to \"identifierType\""
        },
        "intendedcd": {
          "type": "string",
          "description": "Which drug (code) was initially considered ?",
          "examples": ["3356102"]
        },
        "intendedname": {
          "type": "string",
          "description": "Which drug (name) was initially considered ?",
          "examples": ["Rhinathiol Naturactiv Pulmo 133Ml"]
        },
        "deliveredcd": {
          "type": "string",
          "description": "Which drug (code) was delivered ?",
          "examples": ["3319522"]
        },
        "deliveredname": {
          "type": "string",
          "description": "Which drug (name) was delivered ?",
          "examples": ["Orgitan Care B+Pharma 90 Tabl"]
        },
        "eanIdentifier": {
          "type": "string",
          "description": "EAN identifier (not possible anymore)",
          "examples": ["8712412561551"],
          "deprecated": true
        },
        "compoundprescriptionText": {
          "type": "string",
          "description": "text of the component prescription",
          "examples": ["Free text drug"]
        },
        "comment": {
          "type": "string",
          "description": "comment put at root level, to express adaptation or CD-EAN case"
        },
        "beginmoment": {
          "type": "string",
          "description": "When to take drug, or when starts suspension ? (format is \"YYYY-MM-DD\")",
          "examples": ["2022-09-16"],
          "format": "date"
        },
        "endmoment": {
          "type": "string",
          "description": "When to end drug, or when stops suspension ? Format is \"YYYY-MM-DD\" FYI : Date is inclusive (so with my example, nothing after \"2022-09-17\")",
          "examples": ["2022-09-16"],
          "format": "date"
        },
        "lifecycle": {
          "type": "string",
          "enum": ["suspended", "stopped"],
          "description": "Used in suspension context :\n- \"suspended\": a temporary suspension\n- \"stopped\": a definitive suspension",
          "examples": ["suspended"]
        },
        "duration": {
          "$ref": "#/definitions/TreatmentDuration",
          "description": "Duration of treatment Example : for 3 months"
        },
        "temporality": {
          "type": "string",
          "enum": ["acute", "chronic", "oneshot"]
        },
        "periodicity": {
          "$ref": "#/definitions/Periodicity",
          "description": "periodicity in frequency"
        },
        "posologyFreeText": {
          "type": ["string", "null"],
          "description": "Free text posology. If set to null, default value won't be used & tag \\<posology\\> won't be included in payload",
          "examples": ["To take when you want"],
          "default": "Free text posology"
        },
        "regimen": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/RegimenPosology"
          },
          "description": "Codified posology (regimen)"
        },
        "route": {
          "$ref": "#/definitions/AdministrationRoute",
          "description": "Administration route",
          "examples": ["00001"]
        },
        "instructionForPatient": {
          "type": "string",
          "description": "Instructions for patient",
          "examples": ["Take with water"]
        },
        "medicationuse": {
          "type": "string",
          "description": "Why we need that drug ?",
          "examples": ["For heart issues"]
        },
        "begincondition": {
          "type": "string",
          "description": "When to begin treatment ?",
          "examples": ["When you feel the need"]
        },
        "endcondition": {
          "type": "string",
          "description": "When to finish treatment ?",
          "examples": ["When you don't feel the need"]
        }
      },
      "additionalProperties": false
    },
    "TreatmentDuration": {
      "type": "object",
      "properties": {
        "quantity": {
          "type": "number"
        },
        "timeunit": {
          "type": "string",
          "enum": ["a", "d", "hr", "min", "mo", "ms", "ns", "s", "us", "wk"]
        }
      },
      "required": ["quantity", "timeunit"],
      "additionalProperties": false
    },
    "Periodicity": {
      "type": "string",
      "enum": [
        "D",
        "DA",
        "DD",
        "DE",
        "DN",
        "DQ",
        "DT",
        "DV",
        "DW",
        "DX",
        "DZ",
        "J",
        "JD",
        "JH2",
        "JQ",
        "JT",
        "JV",
        "JZ",
        "M",
        "MA",
        "MC",
        "MD",
        "ME",
        "MN",
        "MQ",
        "MS",
        "MT",
        "MV",
        "MX",
        "MZ2",
        "O1",
        "U",
        "UA",
        "UD",
        "UH",
        "UT",
        "UV",
        "UW",
        "UZ",
        "W",
        "WA",
        "WD",
        "WE",
        "WN",
        "WP",
        "WQ",
        "WS",
        "WT",
        "WV",
        "WW",
        "WX",
        "WZ"
      ]
    },
    "RegimenPosology": {
      "type": "object",
      "properties": {
        "quantity": {
          "type": ["number", "string"],
          "description": "Quantity",
          "examples": [2.5]
        },
        "unit": {
          "$ref": "#/definitions/AdministrationUnit",
          "description": "Unit",
          "examples": ["00001"]
        },
        "timeOfDay": {
          "type": "object",
          "properties": {
            "time": {
              "type": "string",
              "description": "Time (\"HH:MM:SS\")",
              "examples": ["08:17:42"],
              "pattern": "^(0\\d|1\\d|2[0-3]):[0-5]\\d:[0-5]\\d(\\.\\d{1,3})?((\\+|-)(0\\d|1[0-2]):[0-5]\\d|Z)?$"
            },
            "dayPeriod": {
              "$ref": "#/definitions/DayPeriod",
              "description": "Day period",
              "examples": ["morning"]
            }
          },
          "additionalProperties": false,
          "description": "Time of the day : either <time> OR <dayperiod>"
        },
        "dayIngestion": {
          "type": "object",
          "properties": {
            "date": {
              "type": "string",
              "description": "Option 1 : date (YYYY-MM-DD)",
              "format": "date"
            },
            "weekday": {
              "$ref": "#/definitions/Weekday",
              "description": "Option 2 : weekday",
              "examples": ["monday"]
            },
            "dayNumber": {
              "type": "number",
              "description": "Option 3 : day number",
              "examples": [1],
              "minimum": 1
            }
          },
          "additionalProperties": false,
          "description": "Day of ingestion : this can be included in various ways"
        }
      },
      "required": ["quantity", "timeOfDay"],
      "additionalProperties": false
    },
    "AdministrationUnit": {
      "type": "string",
      "enum": [
        "00001",
        "00002",
        "00003",
        "00004",
        "00005",
        "00006",
        "00007",
        "00008",
        "00009",
        "00010",
        "00011",
        "00012",
        "00013",
        "00014",
        "00015",
        "00016",
        "00017",
        "00018",
        "00019",
        "00020",
        "00021",
        "00022",
        "00023",
        "00024",
        "00025",
        "00026",
        "00027",
        "00028",
        "00029",
        "00030",
        "cm",
        "dropsperminute",
        "gm",
        "internationalunits",
        "mg",
        "mg/ml",
        "mck/h",
        "mck/kg/minute",
        "measure",
        "mg/h",
        "ml/h",
        "tbl",
        "tsp",
        "unt/h"
      ]
    },
    "DayPeriod": {
      "type": "string",
      "enum": [
        "afterbreakfast",
        "afterdinner",
        "afterlunch",
        "beforebreakfast",
        "beforedinner",
        "beforelunch",
        "betweenbreakfastandlunch",
        "betweenlunchanddinner",
        "betweendinnerandsleep",
        "duringbreakfast",
        "duringdinner",
        "duringlunch",
        "morning",
        "thehourofsleep"
      ]
    },
    "Weekday": {
      "type": "string",
      "enum": [
        "monday",
        "tuesday",
        "wednesday",
        "thursday",
        "friday",
        "saturday",
        "sunday"
      ]
    },
    "AdministrationRoute": {
      "type": "string",
      "enum": [
        "00001",
        "00002",
        "00003",
        "00004",
        "00005",
        "00006",
        "00007",
        "00008",
        "00009",
        "00010",
        "00011",
        "00012",
        "00013",
        "00014",
        "00015",
        "00016",
        "00017",
        "00018",
        "00019",
        "00020",
        "00021",
        "00022",
        "00023",
        "00024",
        "00025",
        "00026",
        "00027",
        "00028",
        "00029",
        "00030",
        "00031",
        "00032",
        "00033",
        "00034",
        "00035",
        "00036",
        "00037",
        "00038",
        "00039",
        "00040",
        "00041",
        "00042",
        "00043",
        "00044",
        "00045",
        "00046",
        "00047",
        "00048",
        "00049",
        "00050",
        "00051",
        "00052",
        "00053",
        "00054",
        "00055",
        "00056",
        "00057",
        "00058",
        "00059",
        "00060",
        "00061",
        "00062",
        "00063",
        "00064",
        "00065",
        "00066",
        "00067",
        "00068",
        "00069",
        "00070",
        "00071",
        "00072",
        "00073",
        "both_ears",
        "both_eyes",
        "both_nostrils",
        "cutaneous_injection",
        "derm",
        "dermal_injection",
        "ear_left",
        "ear_right",
        "eye_left",
        "eye_right",
        "hyperdermoclyse",
        "icut",
        "ider",
        "larter",
        "nose_left",
        "nose_right",
        "oft",
        "transdermal",
        "vitreal_injection"
      ]
    }
  }
}

=== smals-jy/KMEHR-tests/configurations/fhir-dosage/TS-06.json
{
  "drugType": "compoundprescription",
  "compoundprescriptionText": "Drug nÂ°6",
  "posologyFreeText": "Free text posology",
  "beginmoment": "2021-03-22",
  "endmoment": "2021-03-22",
  "medicationuse": "Free text without periodicity / temporality but with endDate - only displayed the 22nd maart 2021"
}

=== smals-jy/KMEHR-tests/configurations/fhir-dosage/TS-09.json
{
  "drugType": "compoundprescription",
  "compoundprescriptionText": "Drug nÂ°9",
  "beginmoment": "2021-03-22",
  "regimen": [
    {
      "quantity": 2,
      "timeOfDay": {
        "dayPeriod": "beforebreakfast"
      },
      "dayIngestion": {
        "weekday": "friday"
      }
    }
  ],
  "medicationuse": "Regimen posology without frequency (2 teaspoon (5 ml) ) - only displayed the 26nd maart 2021 (Friday)"
}

=== smals-jy/KMEHR-tests/configurations/fhir-dosage/TS-10.json
{
  "drugType": "compoundprescription",
  "compoundprescriptionText": "Drug nÂ°10",
  "beginmoment": "2021-03-22",
  "periodicity": "D",
  "temporality": "chronic",
  "regimen": [
    {
      "quantity": 1,
      "timeOfDay": {
        "time": "05:59:00"
      }
    },
    {
      "quantity": 1,
      "timeOfDay": {
        "time": "07:30:00"
      }
    },
    {
      "quantity": 1,
      "timeOfDay": {
        "time": "13:30:00"
      }
    },
    {
      "quantity": 1,
      "timeOfDay": {
        "time": "19:30:00"
      }
    },
    {
      "quantity": 1,
      "timeOfDay": {
        "time": "22:30:00"
      }
    }
  ],
  "medicationuse": "Regimen posology with frequency (2) - daily hours - morning / noon / afterlunch / sleep"
}
